services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=microservices'
      - 'MYSQL_PASSWORD=docker'
      - 'MYSQL_ROOT_PASSWORD=docker'
      - 'MYSQL_USER=root'
    ports:
      - '3307'
